// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ClubTagsagKonzolos;
//
//    var members = Members.FromJson(jsonString);

namespace ClubTagsagKonzolos
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Text.Json.Serialization;
    using System.Linq;
    using System.Text;
    using System.Threading.Tasks;

    public partial class Members
    {
        [JsonProperty("id")]
        public int Id { get; set; }

        [JsonProperty("entry")]
        public string Entry { get; set; }

        [JsonProperty("rating")]
        public int Rating { get; set; }

        [JsonProperty("fullname")]
        public string Fullname { get; set; }

        [JsonProperty("interest")]
        public string Interest { get; set; }

        public override string ToString()
        {
            return Fullname;
        }
    }

    public partial class Members
    {
        public static Members[] FromJson(string json) => JsonConvert.DeserializeObject<Members[]>(json, Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            }
        };
    }       
}
